quotes = [
    '"Be yourself; everyone else is already taken."',
    '“Be who you are and say what you feel, because those who mind don’t matter,\nand those who matter don’t mind.”',
    '“You only live once, but if you do it right, once is enough.”',
    '“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.”',
    '“It is better to be hated for what you are than to be loved for what you are not.”',
    '“Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect).”',
    '“Life is what happens to us while we are making other plans.”',
    '“I may not have gone where I intended to go, but I think I have ended up where I needed to be.”',
    '“If you don’t stand for something you will fall for anything.”',
    '“You have gotta dance like there is nobody watching, Love like you wll never be hurt,\nSing like there is nobody listening, And live like it is heaven on earth.”',
    '“Fairy tales are more than true: not because they tell us that dragons exist,\nbut because they tell us that dragons can be beaten.”',
    '“It is never too late to be what you might have been.”',
    '“Everything you can imagine is real.”',
    '“Life isnt about finding yourself. Life is about creating yourself.”',
    '“Do what you can, with what you have, where you are.”',
    '"ak jedna kapitola skončila, neznamená to, že je koniec.\n Len to, že si vstúpila do novej kapitoly života."',
    '“And, when you want something, all the universe conspires in helping you to achieve it.”',
    '“It’s no use going back to yesterday, because I was a different person then.”',
    '“Do what you feel in your heart to be right – for you’ll be criticized anyway.”',
    '“I can’t give you a sure-fire formula for success, but I can give you a formula for failure: \n try to please everybody all the time.”',
    '“Happiness is not something ready made. It comes from your own actions.”',
    '"Nikdy neprenásleduj štastie akokoľvek šialené sa ti to môže zdať.\nKedže štastie je len vedlajší produkt tvojích akcií."',
    '“Peace begins with a smile..”',
    '“Do not read, as children do, to amuse yourself, or like the ambitious,\n for the purpose of instruction. No, read in order to live.”',
    '“Friendship is unnecessary, like philosophy, like art....\nIt has no survival value; rather it is one of those things which give value to survival.”',
    '“Instead of worrying about what you cannot control, shift your energy to what you can create.”',
    '“Accept yourself, love yourself, and keep moving forward. \nIf you want to fly, you have to give up what weighs you down.”',
    '“Believe in yourself. You are braver than you think, more talented than you know,\n and capable of more than you imagine.”',
    '“Life is about accepting the challenges along the way,\n choosing to keep moving forward, and savoring the journey.”',
    '"Though nobody can go back and make a new beginning... Anyone can start over and make a new ending.”',
    '“Sometimes you have to lose all you have to find out who you truly are.”',
    '“Count your age by friends, not years. Count your life by smiles, not tears.”',
    '“Turn your wounds into wisdom.”',
    '“The simple things are also the most extraordinary things, and only the wise can see them.”',
    '“You do not write your life with words...You write it with actions.\n What you think is not important. It is only important what you do.”',
    '"Necíť sa zle ak niečomu nerozumieš, Necíť sa zle ak si preťažená niečím.\nNadých a výdych, späť do práce."',
    '“You will do foolish things, but do them with enthusiasm.”',
    '“The past has no power over the present moment.”',
    '“The only way to get through life is to laugh your way through it. You either have to laugh or cry.\n I prefer to laugh. Crying gives me a headache.”',
    '“The possession of knowledge does not kill the sense of wonder and mystery. There is always more mystery.”',
    '“For every minute you are angry you lose sixty seconds of happiness.”',
    '“Time you enjoy wasting is not wasted time.”',
    '"Nikdy na toto obdobie nezabudnem. To ti slubujem. 2022.12.25 - Lukas"',
    '"Ak sa mi to podarí, tak otvor túto aplikáciu aj 21.1.2024. Pochopíš neskor."',
    '“Take responsibility of your own happiness, never put it in other people’s hands.”',
    '“It isn’t what you have or who you are or where you are or what you are doing \nthat makes you happy or unhappy. It is what you think about it.”',
    '“Let us be grateful to the people who make us happy;\n they are the charming gardeners who make our souls blossom.”',
    '“Keep Going. Your hardest times often lead to the greatest moments of your life. \n Keep going. Tough situations build strong people in the end.”',
    '“When we are no longer able to change a situation, we are challenged to change ourselves.”',
    '“An abnormal reaction to an abnormal situation is normal behavior.”',
    '“Ultimately, man should not ask what the meaning of his life is, but rather must recognize that it is he who is asked. \n In a word, each man is questioned by life; and he can only answer to life by answering for his own life; to life he can only respond by being responsible.”',
    '"Kindness doesn’t cost anything, but means everything."'
]

exports.quotes = quotes;